kind: Service
apiVersion: v1
metadata:
  name: newTest
  labels:
    app: newTest
spec:
  type: ClusterIP
  selector:
    app: newTest
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: newTest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newTest
  template:
    metadata:
      labels:
        app: newTest
        version: v1
    spec:
      containers:
      - name: newTest
        image: newTest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
